"""Domain model for telemetry events produced by the Edge application.

This module contains business data structures only. It deliberately avoids
networking and persistence concerns so that telemetry events remain independent
from the infrastructure used to store or transmit them.
"""

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any


@dataclass(frozen=True)
class TelemetryEvent:
    """Immutable business event generated by the Edge application."""

    event_type: str
    payload: dict[str, Any]
    created_at: str

    @classmethod
    def harsh_braking(
        cls,
        acc_y: float,
        timestamp: int | float,
    ) -> "TelemetryEvent":
        """Create a telemetry event describing a harsh braking event."""
        return cls(
            event_type="harsh_braking",
            payload={
                "timestamp": timestamp,
                "acc_y": acc_y,
            },
            created_at=datetime.now(timezone.utc).isoformat(),
        )